server:
  port: 7003
  error:
    include-message: always
spring:
  data:
    mongodb:
      authentication-database: admin
      username: rootuser
      password: rootpass
      database: mongodb_db
      port: 27017
      host: localhost
      auto-index-creation: true